version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: web

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html
    container_name: php

  composer:
    image: composer
    volumes:
      - ./src/:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer", "--ignore-platform-reqs"]
    container_name: composer
    profiles: [ "ignore" ]

  mail:
    image: mailhog/mailhog
    user: root
    restart: always
    tty: true
    privileged: true
    ports:
      - 1025:1025
      - 8025:8025
    command: [ "-storage=maildir", "-maildir-path=/maildir" ]
    volumes:
      - mail_data:/maildir
    container_name: mail

volumes:
  mail_data:
    driver: local